### ISSUE TITLE
Problems under cygwin with out of tree repository

### ISSUE THREAD

**Issue by RedX2501** [msiemens/PyGitUp#31]
I have a .git file with a path to my gitdir. This path is in windows format so i can use git under windows also but git-up does not seem to like or understand it when using it under cygwin: Using it in the powershell it seems to work.

![2015-07-14_09-51-07](https://cloud.githubusercontent.com/assets/929932/8668783/fa5bba16-2a0e-11e5-96cf-51c7cb4d82ed.png)

**Comment by msiemens** [comment]
Interesting. Could you post the result from running `git rev-parse --show-toplevel` in this directory? And could you try running PyGitUp from Windows' `cmd.exe`?

**Comment by RedX2501** [comment]
Under cmd.exe and powershell.exe it seems to work.

![2015-07-15_18-44-57](https://cloud.githubusercontent.com/assets/929932/8704185/c17088a8-2b21-11e5-898c-68f549b98de5.png)

**Comment by msiemens** [comment]
Okay, what's the result of `git rev-parse --show-toplevel` on Cygwin, CMD and Powershell?

**Comment by RedX2501** [comment]
Powershell:
> D:/_P/(obscured)/SW/50_Implementation

Cygwin:
> /cygdrive/d/_P/(obscured)/SW/50_Implementation

`git rev-parse --git-dir` yields:

Powershell:
> D:/Git_repos/out_of_tree/repo_name.git

Cygwin:
> /cygdrive/d/Git_repos/out_of_tree/repo_name.git

**Comment by msiemens** [comment]
Just out of curiosity, what happens, if you use `/cygdrive/d/Git_repos/out_of_tree/repo_name.git` in your `.git` file instead of `D:/Git_repos/out_of_tree/repo_name.git`?

**Comment by msiemens** [comment]
@RedX2501 Is this still relevant?

**Comment by RedX2501** [comment]
Tried it out with 1.4.0 and still the same behaviour.
```
Traceback (most recent call last):
  File "/usr/bin/git-up", line 9, in <module>
    load_entry_point('git-up==1.4.0', 'console_scripts', 'git-up')()
  File "/usr/lib/python2.7/site-packages/PyGitUp/gitup.py", line 599, in run
    gitup = GitUp()
  File "/usr/lib/python2.7/site-packages/PyGitUp/gitup.py", line 156, in __init__
    odbt=GitCmdObjectDB)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 165, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /cygdrive/d/(...)Implementation
```

Output with a cygwin path produces a correct git-up error message:
`
Can't update your repo because it doesn't has any branches with tracking information.
`

**Comment by msiemens** [comment]
> Output with a cygwin path produces a correct git-up error message:

You mean when using a cygwin path in the `.git` file?

**Comment by RedX2501** [comment]
Yes

**Comment by msiemens** [comment]
Which console did you use? PowerShell or the Cygwin shell? If it's with both, this problem is fixed, isn't it?

**Comment by msiemens** [comment]
Just a quick heads up: GitPython v2.1.0 promises to improve Cygwin support (see [this PR](https://github.com/gitpython-developers/GitPython/pull/533)). It seems to improve path handling with Cygwin so maybe it fixes this problem. Could you update GitPython (`pip install -U GitPython`) and see if the problem is fixed?

**Comment by msiemens** [comment]
Closing due to inactivity, feel free to re-open if this is still an issue.
