### ISSUE TITLE
unable to install on Synology NAS

### ISSUE THREAD

**Issue by jpage4500** [msiemens/PyGitUp#33]
Hi, I was really hopeful I could get this to install on my Synology NAS DS-214. It has Python and git support.

Looking at the error message it appears to be a problem with 'six-1.7.3' so maybe not related to git-up at all.. just hoping someone might have a suggestion.

Here's what I did and see.

````
~$ python
Python 2.7.9 (default, Jun  3 2015, 05:41:35)
[GCC 4.6.4] on linux2
````

````
~$ python -m pip install git-up
Collecting git-up
  Downloading git-up-1.3.0.zip
Collecting GitPython==1.0.0 (from git-up)
  Downloading GitPython-1.0.0.tar.gz (354kB)
    100% |████████████████████████████████| 356kB 154kB/s
Collecting colorama==0.3.3 (from git-up)
  Downloading colorama-0.3.3.tar.gz
Collecting termcolor==1.1.0 (from git-up)
  Downloading termcolor-1.1.0.tar.gz
Collecting docopt==0.6.2 (from git-up)
  Downloading docopt-0.6.2.tar.gz
Collecting six==1.9.0 (from git-up)
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting gitdb>=0.6.4 (from GitPython==1.0.0->git-up)
  Downloading gitdb-0.6.4.tar.gz (400kB)
    100% |████████████████████████████████| 401kB 141kB/s
Collecting smmap>=0.8.5 (from gitdb>=0.6.4->GitPython==1.0.0->git-up)
  Downloading smmap-0.9.0.tar.gz
Installing collected packages: smmap, gitdb, GitPython, colorama, termcolor, docopt, six, git-up
  Running setup.py install for smmap
  Running setup.py install for gitdb
  Running setup.py install for GitPython
  Running setup.py install for colorama
  Running setup.py install for termcolor
  Running setup.py install for docopt
  Found existing installation: six 1.7.3
    Uninstalling six-1.7.3:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/req/req_install.py", line 726, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/utils/__init__.py", line 314, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 232, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 230, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
````

**Comment by jpage4500** [comment]
nevermind.. I figured out how to upgrade 'six' separately.. 

easy_install --upgrade six

**Comment by msiemens** [comment]
Strange... Maybe a problem with pip?

**Comment by moontear** [comment]
Had the same problem/error. Everything in `/usr/local/lib/python2.7/site-packages` is symlinked to `/volume1/@appstore/PythonModule/usr/lib/python2.7`. This sometimes throws `pip` off sometimes `easy_install` on upgrading. Easiest solution seems to be to simply remove the package from `site-packages` and reinstall.
