### ISSUE TITLE
git up --version return an error about JSON object

### ISSUE THREAD

**Issue by GuilloOme** [msiemens/PyGitUp#43]
When I call `git up --version`, I get :
```
$ git up --version
GitUp version is: v1.3.0
Checking for updates...Traceback (most recent call last):
  File "/usr/local/bin/git-up", line 9, in <module>
    load_entry_point('git-up==1.3.0', 'console_scripts', 'git-up')()
  File "/usr/local/bin/gitup.py", line 579, in run
    GitUp(sparse=True).version_info()
  File "/usr/local/bin/gitup.py", line 393, in version_info
    details = json.load(urlopen(PYPI_URL))
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by msiemens** [comment]
Which version of Python do you use? Python 2 oder 3?

**Comment by msiemens** [comment]
And if I'm not mistaken, this is the same issue as #34 which was fixed in v1.3.1.

**Comment by GuilloOme** [comment]
Yes you're right looks the same… I thought that because I installed it throw `pip`, I've got the lastest version but it seems that was not the case.
Thank you for your time !

**Comment by msiemens** [comment]
You're welcome!
