### ISSUE TITLE
git-up doesn't work for MINGW32

### ISSUE THREAD

**Issue by balbusm** [msiemens/PyGitUp#50]
Hi,
I found two problems to run PyGitUP.
I have Git Bash version 1.8.4-preview20130916 based on MINGW32 and Windows Python 3.3 installed.

```
Running git-up in git repo causes:
Traceback (most recent call last):
  File "c:\program files (x86)\python33\lib\subprocess.py", line 1106, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\git\cmd.py", line 623, in execute
    **subprocess_kwargs
  File "c:\program files (x86)\python33\lib\subprocess.py", line 820, in __init__
    restore_signals, start_new_session)
  File "c:\program files (x86)\python33\lib\subprocess.py", line 1112, in _execute_child
    raise WindowsError(*e.args)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python33\lib\runpy.py", line 160, in _run_module_
as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files (x86)\python33\lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\AppData\Roaming\Python\Scripts\git-up.exe\__main__.py", line 9, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\PyGitUp\gitup.py", line 599, in run
    gitup = GitUp()
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\PyGitUp\gitup.py", line 199, in __init__
    self.git.status(porcelain=True, untracked_files='no').split(
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\PyGitUp\git_wrapper.py", line 123, in <lambda>
    return lambda *args, **kwargs: self.run(name, *args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\PyGitUp\git_wrapper.py", line 92, in run
    cmd = getattr(self.git, name)(as_process=True, *args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\git\cmd.py", line 463, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\git\cmd.py", line 906, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python33\site-packages\git\cmd.py", line 626, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: [WinError 2] The system cannot find the file specified
Exception TypeError: TypeError("'NoneType' object is not iterable",) in <bound method GitWrapper.__del__ of <PyGitUp.git_wrapper.GitWrapper object at 0x0357DCB0>> ignored

I managed to solve it by setting USE_SHELL = True in Python33\site-packages\git\cmd.py
In every place where subprocess is called it is required to use shell.
Could you change it?
```

Even if I added shell=true, I'm getting (git is on the PATH):

```
'git' is not recognized as an internal or external command,
operable program or batch file.
```

It looks like Linux PATH is passed to Windows console, so entire PATH entry is unrecognized.
Echoing PATH confirms it.
Could you also convert Linux PATH to Windows before executing shell command?

BTW. git-up works well under Windows console

**Comment by msiemens** [comment]
Using Windows Python from MinGW will always cause trouble. The proper solution here would be to install the MinGW version of Python and install PyGitUp from there. Still, I'm not sure if the MinGW installation provided by Git Bash even provides a package manager.

Maybe you can create a proxy cmd script that launches PyGitUp? As far as I can see this way MinGW would start the Windows console which in turn would properly launch PyGitUp. See my [comment here](https://github.com/msiemens/PyGitUp/issues/39#issuecomment-157153003) for details. Does this fix the problem?

> I managed to solve it by setting USE_SHELL = True in Python33\site-packages\git\cmd.py In every place where subprocess is called it is required to use shell. Could you change it?

`git/cmd.py` is a 3rd party library we depend on, I have no influence on it.
