### ISSUE TITLE
Git-up fails with KeyError

### ISSUE THREAD

**Issue by kontinuity** [msiemens/PyGitUp#53]
Using `git-up` with no options (1.4.1):

```
Traceback (most recent call last):
  File "/Users/redacted/bin/git-up", line 11, in <module>
    sys.exit(run())
  File "/Users/redacted/lib/python2.7/site-packages/PyGitUp/gitup.py", line 600, in run
    if arguments['--no-fetch'] or arguments['--no-f']:
KeyError: '--no-f'
```

**Comment by msiemens** [comment]
Thanks for reporting! Should be fixed in v.1.4.2
