### ISSUE TITLE
PyGitUp breaking on conflicts with GitPython 2.1.0

### ISSUE THREAD

**Issue by fbcbarbosa** [msiemens/PyGitUp#57]
Hello,

I have been experiencing errors with the latest version of PyGitUp (1.4.2) and GitPython (2.1.0) whenever there are conflicts between my local files and the remote. Here's what happens when there is a conflict:

```
$ git up
Fetching origin
stashing 1 change
Traceback (most recent call last):
  File "/home/dev/.pyenv/versions/2.7.9/bin/git-up", line 11, in <module>
    sys.exit(run())
  File "/home/dev/.pyenv/versions/2.7.9/lib/python2.7/site-packages/PyGitUp/gitup.py", line 605, in run
    gitup.run()
  File "/home/dev/.pyenv/versions/2.7.9/lib/python2.7/site-packages/PyGitUp/gitup.py", line 213, in run
    with self.git.stash():
  File "/home/dev/.pyenv/versions/2.7.9/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/dev/.pyenv/versions/2.7.9/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 147, in stash
    self.run('stash')
  File "/home/dev/.pyenv/versions/2.7.9/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 118, in run
    raise GitError(message, stderr=error.stderr, stdout=stdout)
  File "/home/dev/.pyenv/versions/2.7.9/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 230, in __init__
    super(GitError, self).__init__(None, None, stderr)
  File "/home/dev/.local/lib/python2.7/site-packages/git/exc.py", line 74, in __init__
    super(GitCommandError, self).__init__(command, status, stderr, stdout)
  File "/home/dev/.local/lib/python2.7/site-packages/git/exc.py", line 38, in __init__
    command = command.split()
AttributeError: 'NoneType' object has no attribute 'split'
```

Rolling back my installation of GitPython to 2.0.8 fixed the issue. Note that I'm use Python 2.7.9 with PyEnv.

I was in doubt if I should open this issue to GitPython instead, but decided to report it here, to see if other people are experiencing the same problem with git up. If so, maybe you could document it, or add a requirement that GitPython < 2.1.0?

**Comment by msiemens** [comment]
Hey, thanks for reporting! Seems to be the same issuse as #56 which was fixed, but somehow I forgot to release a new version. A new version has been released now which includes the fix :)

**Comment by fbcbarbosa** [comment]
Hi @msiemens, good to know, thanks! :)
