### ISSUE TITLE
GitPython issues with packed-ref format in Git 2.15+

### ISSUE THREAD

**Issue by pleunv** [msiemens/PyGitUp#65]
As of Git 2.15 GitPython has some issues with the new format of packed-ref headers, resulting in PyGitUp crashing whenever doing  a `git up`.

```
$ git up
Traceback (most recent call last):
  File "C:\Users\Pleun\AppData\Local\scoop\apps\python\3.5.1\scripts\git-up-script.py", line 9, in <module>
    load_entry_point('git-up==1.3.0', 'console_scripts', 'git-up')()
  File "c:\users\pleun\appdata\local\scoop\apps\python\3.5.1\lib\site-packages\git_up-1.3.0-py3.5.egg\EGG-INFO\scripts\gitup.py", line 585, in run
    gitup = GitUp()
  File "c:\users\pleun\appdata\local\scoop\apps\python\3.5.1\lib\site-packages\git_up-1.3.0-py3.5.egg\EGG-INFO\scripts\gitup.py", line 147, in __init__
    if not any(b.tracking_branch() for b in self.repo.branches):
  File "C:\Users\Pleun\AppData\Local\scoop\apps\python\3.5.1\lib\site-packages\gitpython-1.0.0-py3.5.egg\git\repo\base.py", line 237, in heads
    return Head.list_items(self)
  File "C:\Users\Pleun\AppData\Local\scoop\apps\python\3.5.1\lib\site-packages\gitpython-1.0.0-py3.5.egg\git\util.py", line 714, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "C:\Users\Pleun\AppData\Local\scoop\apps\python\3.5.1\lib\site-packages\gitpython-1.0.0-py3.5.egg\git\refs\symbolic.py", line 594, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):
  File "C:\Users\Pleun\AppData\Local\scoop\apps\python\3.5.1\lib\site-packages\gitpython-1.0.0-py3.5.egg\git\refs\symbolic.py", line 98, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

See https://github.com/gitpython-developers/GitPython/issues/687 and the PR https://github.com/gitpython-developers/GitPython/pull/689. I'm guessing PyGitUp will need a version bump when a new GitPython version gets released.

**Comment by msiemens** [comment]
Thanks for the heads-up! I'll keep track of the issue and bump the dependency when GitPython is updated.

**Comment by mbenatti** [comment]
#https://github.com/gitpython-developers/GitPython/issues/687

**Comment by mbenatti** [comment]
https://github.com/gitpython-developers/GitPython/issues/687

**Comment by rvanginneken** [comment]
> Thanks for the heads-up! I'll keep track of the issue and bump the dependency when GitPython is updated.

I think that time is here. I'm now encountering this issue after an apt update on buntu 16.04.

**Comment by msiemens** [comment]
> I think that time is here. I'm now encountering this issue after an apt update on buntu 16.04.

As far as I can see, no new version of GitPython has been released so far. As a workaround installing GitPython from master seems to work:

```bash
$ pip install -U git+ssh://git@github.com/gitpython-developers/GitPython.git
```

Can someone confirm this works?

**Comment by pleunv** [comment]
Confirmed, this works!

**Comment by mbenatti** [comment]
Here worked with this command: (the comand by @msiemens I got permission denied)

`$ sudo pip install -U git+http://github.com/gitpython-developers/GitPython.git`

**Comment by tim-mc** [comment]
Alternative method:

Clone repo

```bash
git clone https://github.com/gitpython-developers/GitPython
cd GitPython
git submodule update --init --recursive
./init-tests-after-clone.sh
```

Install GitPython

```
python setup.py install
```

Install `git-up`

```
pip install git-up
```

**Comment by hugovk** [comment]
See https://github.com/gitpython-developers/GitPython/issues/704 about a new GitPython release.

**Comment by hugovk** [comment]
GitPython 2.18 is now out with the fix. 

https://github.com/gitpython-developers/GitPython/issues/687#issuecomment-350780349
