### ISSUE TITLE
Seeing kernel_require.rb:55:in `require': libruby.so.2.2

### ISSUE THREAD

**Issue by ykoer** [msiemens/PyGitUp#66]
I am seeing following error after update to Fedora 27.
`/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require': libruby.so.2.2: cannot open shared object file: No such file or directory - /usr/local/lib64/gems/ruby/posix-spawn-0.3.11/posix_spawn_ext.so (LoadError)`

ruby -v
> ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

bundle -v
> Bundler version 1.16.0

gem -v
> 2.6.4

Any tip how I can make it work under Fedora 27?

Thanks
Yusuf

**Comment by msiemens** [comment]
Hey, I think you mean [`git-up`](https://github.com/aanand/git-up/) which is implemented in Ruby, not `PyGitUp` which is the Python port

**Comment by ykoer** [comment]
I apologize for this. I still had the ruby based script in my bin folder.
Thanks a lot

**Comment by msiemens** [comment]
No worries. Is this fixed for you, then?

**Comment by msiemens** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue.
