### ISSUE TITLE
Exception: PackingType of packed-Refs not understood

### ISSUE THREAD

**Issue by digitalmaster** [msiemens/PyGitUp#67]
I've been using this package for year and but recently started getting this error each time i try to run `git up`. Any thoughts on why this could be happening?

```python
Traceback (most recent call last):
  File "/usr/local/bin/git-up", line 11, in <module>
    sys.exit(run())
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyGitUp/gitup.py", line 608, in run
    gitup = GitUp()
  File "/usr/local/lib/python2.7/site-packages/PyGitUp/gitup.py", line 142, in __init__
    if not any(b.tracking_branch() for b in self.repo.branches):
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/git/repo/base.py", line 267, in heads
    return Head.list_items(self)
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/git/util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/git/refs/symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/Users/josebrowne/Library/Python/2.7/lib/python/site-packages/git/refs/symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

Best

**Comment by msiemens** [comment]
Hey @digitalmaster, this is a problem with the `GitPython` dependency and has already been reported at #65 which also contains a few ways to work around this issue.
