### ISSUE TITLE
If using Python 3 and run from within SourceTree Custom Actions, throws "RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment."

### ISSUE THREAD

**Issue by sompylasar** [msiemens/PyGitUp#72]
```
Traceback (most recent call last):
  File "/usr/local/bin/git-up", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales where
discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
```

**Comment by sompylasar** [comment]
The workaround is to point SourceTree Custom Action to a Bash script that sets the locale and then invokes `git-up`.

[The referenced 'Click' library page](http://click.pocoo.org/python3/) describes why this is needed when using Python 3.

```bash
#!/bin/bash

set -eu

REPO_PATH=$1

if [[ ! -d "${REPO_PATH}" ]]; then
	exit -1
fi

( cd "${REPO_PATH}" && LC_ALL=en_US.utf-8 LANG=en_US.utf-8 /usr/local/bin/git-up )
```

**Comment by msiemens** [comment]
Aside from getting rid of `click` altogether I don't think there's much I can do here. I'm glad you were able to find a workaround, though!

**Comment by WoLpH** [comment]
Actually, it's not pretty but you can do this:
```python
import click
click.disable_unicode_literals_warning = True
```

**Comment by msiemens** [comment]
@sompylasar Do the settings mentioned here https://github.com/msiemens/PyGitUp/issues/72#issuecomment-390988462 fix the issue for you?

**Comment by sompylasar** [comment]
@msiemens I'm using the wrapper script that works regardless of the environment. Changing the environment is too much of an ask, it would affect a lot more than needed.

**Comment by msiemens** [comment]
Can we close the issue then? I know it's only a workaround to use a wrapper script or to change the locale, but I guess it's all we can do for now

**Comment by sompylasar** [comment]
@msiemens @WoLpH Okay, let's close it then.
