### ISSUE TITLE
Incompatible with Click 7.0.0, should restrict dependency to <7.0.0

### ISSUE THREAD

**Issue by antaflos** [msiemens/PyGitUp#82]
It seems click 7.0.0 is quite incompatible with click 6.0.0 so it might be prudent to restrict the dependency on click to >=6.0.0 and <7.0.0.

Otherwise a fresh install of git-up will exhibit problems like this:

```
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/git-up", line 11, in <module>
    sys.exit(run())
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: run() takes exactly 4 arguments (3 given)
```

This is with click 7.0.0 as it is automatically installed by pip when installing git-up. Uninstalling it and installing click 6.0.0 makes git-up work again:

```
pip uninstall click
pip install click==6.0.0
```

**Comment by msiemens** [comment]
Thanks for the report! I've released a version which should fix this 🙃
