### ISSUE TITLE
Re-enable code coverage uploading

### ISSUE THREAD

**Issue by msiemens** [msiemens/PyGitUp#95]
Error:
```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/a1f31144-8dea-4422-b806-992282cb8640.sh
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.4.8/x64/lib/python3.4/site-packages/coveralls/api.py", line 177, in wear
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.4.8/x64/lib/python3.4/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.4.8/x64/lib/python3.4/site-packages/coveralls/cli.py", line 77, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.4.8/x64/lib/python3.4/site-packages/coveralls/api.py", line 180, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

**Comment by msiemens** [comment]
Fixed in 2d2da626f131da2100bcca23015d5b6ba3eedafa
